name: scp _site files
on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags' 
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - run: echo "🎉 The job was automatically triggered by a ${{ secrets.HOST }} event."
    - run: echo "🎉 The job was automatically triggered by a ${{ secrets.SSH_USER }} event."
    - uses: actions/checkout@master
    - name: Copy folder content recursively to remote
      uses: garygrossgarten/github-action-scp@release
      with:
        local: _posts
        remote: /var/www/blog
        host: ${{ secrets.HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
    - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
